### PR TITLE
Add support for monochrome particles

### PR DESCRIPTION
**Pull request by yaacov**
**Description**

Add support for pixie gray particles.

**Screenshot**
peek 2018-02-28 09-27

### CODE REVIEW

**Comment by yaacov** [comment]
@luania Hi,

Thank you for this plugin, I am using particle-fly for a year now with monochrome particles and it is essential for my work. Your update yesterday broke my editor, because I could not work without my monochrome particles. Please add monochrome option, so new updates will not brake my editor.

**Comment by yaacov** [comment]
@luania hi, updated code for 3.3

**Comment by luania** [comment]
Its ok now in 0.3.4

**Comment by yaacov** [comment]
Thanks :sparkles: :sparkling_heart: :cat2:

**Comment by luania** [comment]
I'm sorry I didn't see it these two days

**Pull request merged**
